DROP TABLE IF EXISTS BOOK;
DROP TABLE IF EXISTS COMMENT;
CREATE TABLE BOOK (ID INT PRIMARY KEY AUTO_INCREMENT, NAME VARCHAR(64), AUTHOR VARCHAR(64), PRICE FLOAT);
CREATE TABLE COMMENT (ID INT PRIMARY KEY AUTO_INCREMENT, BOOK_ID INT, CONTENT VARCHAR(255), FOREIGN KEY(BOOK_ID) REFERENCES Book(ID));
INSERT INTO BOOK (NAME, AUTHOR, PRICE) VALUES('Java Book', 'maomao', 12.34);
INSERT INTO BOOK (NAME, AUTHOR, PRICE) VALUES('Ruby book', 'oamoam', 9.82);
INSERT INTO COMMENT (BOOK_ID, CONTENT) VALUES(1, 'nice java book');
INSERT INTO COMMENT (BOOK_ID, CONTENT) VALUES(1, 'a little boring');
INSERT INTO COMMENT (BOOK_ID, CONTENT) VALUES(2, 'worth reading, recommended');