DROP TABLE IF EXISTS BOOK;
DROP TABLE IF EXISTS COMMENT;
CREATE TABLE BOOK (ID INT PRIMARY KEY AUTO_INCREMENT, NAME VARCHAR(64), AUTHOR VARCHAR(64));
CREATE TABLE COMMENT (ID INT PRIMARY KEY AUTO_INCREMENT, BOOK_ID INT, CONTENT VARCHAR(255), AUTHOR VARCHAR(64), FOREIGN KEY(BOOK_ID) REFERENCES Book(ID));
INSERT INTO BOOK (NAME, AUTHOR) VALUES('Java Book', 'maomao');
INSERT INTO BOOK (NAME, AUTHOR) VALUES('Ruby book', 'oamoam');
INSERT INTO COMMENT (BOOK_ID, CONTENT, AUTHOR) VALUES(1, 'nice java book', 'lei.zh');
INSERT INTO COMMENT (BOOK_ID, CONTENT, AUTHOR) VALUES(1, 'a little boring', 'ryan');
INSERT INTO COMMENT (BOOK_ID, CONTENT, AUTHOR) VALUES(2, 'worth reading, recommended', 'Lei');